### ISSUE TITLE
webpacker docs should be updated with what worked here

### ISSUE THREAD

**Issue by thewoolleyman** [thewoolleyman/blueprint-sass-var-spike#1]
See https://github.com/rails/webpacker/issues/1476#issuecomment-507090144

**Comment by jakeNiemiec** [comment]
How would you improve [the docs](https://github.com/rails/webpacker/blob/master/docs/css.md#resolve-url-loader)? It seems like [there is more being expected of `resolve-url-loader` than is actually being provided.](https://github.com/bholloway/resolve-url-loader#why).

Relevant [comment from the creator of `resolve-url-loader`](https://github.com/bholloway/resolve-url-loader/issues/112#issuecomment-459594063)

**Comment by thewoolleyman** [comment]
or [maybe not](https://github.com/rails/webpacker/issues/1476#issuecomment-507504342)
